name: CI/CD

on: push

env:
  NODE_ENV: test
  MYSQL_DATABASE: 'codebarker'
  MYSQL_ROOT_PASSWORD: 'root'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: tests 
        run: docker-compose -f docker-compose.test.yml up --exit-code-from=test
